package com.maxinesworld.featurerewards

enum class WildlifeActivityPeriod { DIURNAL, NOCTURNAL, CREPUSCULAR }
enum class SanctuaryBiomeZone { EMERALD_FOREST_MEADOW, HIGH_CANOPY_CLOUD_SUMMIT, CORAL_LAGOON_FRESHWATER_STREAM }

data class WildlifeHabitatAffinity(
    val badgeId: String, val animalAssetId: String,
    val nameEnglish: String, val nameFilipino: String,
    val primaryHabitatId: String, val alternateHabitatId: String,
    val habitatEnglish: String, val habitatFilipino: String,
    val factEnglish: String, val factFilipino: String,
    val signatureBehavior: String, val activityPeriod: WildlifeActivityPeriod,
    val biomeZone: SanctuaryBiomeZone,
)

object SanctuarySpeciesCatalog {
    val validHabitatIds: Set<String> = SanctuaryCatalog.pieces.map { it.id }.toSet()
    val species = listOf(
        species("badge_mammal_tarsier", "animal_photo_mammal_tarsier", "Philippine tarsier", "Mawmag", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Each of its eyeballs is bigger than its brain - perfect for spotting bugs at night!", "Ang Mawmag ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature moon-eyed jumper behavior", WildlifeActivityPeriod.NOCTURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_tamaraw", "animal_photo_mammal_tamaraw", "Tamaraw", "Tamaraw", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Only about 500 tamaraws are left in the world - all living on one island, Mindoro!", "Ang Tamaraw ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature mindoro mini buffalo behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_visayan_warty_pig", "animal_photo_mammal_visayan_warty_pig", "Visayan warty pig", "Baboy-ramo ng Visayas", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "This pig rocks a spiky mohawk hairstyle and uses its snout to dig for tasty roots!", "Ang Baboy-ramo ng Visayas ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature mohawk forest pig behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_spotted_deer", "animal_photo_mammal_spotted_deer", "Visayan spotted deer", "Usang batik-batik ng Visayas", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Baby spotted deer are born covered in white dots - like a walking starry night sky!", "Ang Usang batik-batik ng Visayas ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature spotted forest star behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_calamian_deer", "animal_photo_mammal_calamian_deer", "Calamian deer", "Calamian deer", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "This deer is a great swimmer and loves splashing between the Calamian islands!", "Ang Calamian deer ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature low-dash deer behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_mouse_deer", "animal_photo_mammal_mouse_deer", "Philippine mouse-deer", "Philippine mouse-deer", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's one of the smallest hoofed animals on Earth - no bigger than a rabbit!", "Ang Philippine mouse-deer ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature tiny stripe sprinter behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_pangolin", "animal_photo_mammal_pangolin", "Palawan pangolin", "Palawan pangolin", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "When scared, it rolls into a tight ball - a living pinecone that even tigers can't open!", "Ang Palawan pangolin ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature scaly roller behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_flying_fox", "animal_photo_mammal_flying_fox", "Giant golden-crowned flying fox", "Giant golden-crowned flying fox", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its wings stretch wider than a 6-year-old is tall - almost 1.7 meters from tip to tip!", "Ang Giant golden-crowned flying fox ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature golden sky giant behavior", WildlifeActivityPeriod.NOCTURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_philippine_warty_pig", "animal_photo_mammal_philippine_warty_pig", "Philippine warty pig", "Philippine warty pig", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Those bumps on its face aren't really warts - they're padding to protect during piggy play fights!", "Ang Philippine warty pig ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature warty snout scout behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_mammal_naked_backed_bat", "animal_photo_mammal_naked_backed_bat", "Philippine naked-backed fruit bat", "Philippine naked-backed fruit bat", "sanctuary-meadow", "sanctuary-path", "Living Sanctuary / Forest Friends", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its wings meet in the middle of its back - making it look like it's wearing a tiny winged cape!", "Ang Philippine naked-backed fruit bat ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature back-wing bat behavior", WildlifeActivityPeriod.NOCTURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_bird_eagle", "animal_photo_bird_eagle", "Philippine eagle", "Agilang Pilipino", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's our national bird! With a 2-meter wingspan, it's one of the largest and rarest eagles on Earth.", "Ang Agilang Pilipino ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature forest king behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_cockatoo", "animal_photo_bird_cockatoo", "Philippine cockatoo", "Philippine cockatoo", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "This all-white parrot flashes bright red tail feathers when it flies - like a surprise firework!", "Ang Philippine cockatoo ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature red-tail star behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_peacock_pheasant", "animal_photo_bird_peacock_pheasant", "Palawan peacock-pheasant", "Palawan peacock-pheasant", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its tail feathers shimmer with blue-green eye spots that look just like sparkling jewels!", "Ang Palawan peacock-pheasant ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature sparkle tail behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_duck", "animal_photo_bird_duck", "Philippine duck", "Philippine duck", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "When sunlight hits its wings, they flash green, blue, and purple - a flying rainbow!", "Ang Philippine duck ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature rainbow wing behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_eagle_owl", "animal_photo_bird_eagle_owl", "Philippine eagle-owl", "Philippine eagle-owl", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its huge orange eyes can spot a mouse from a football field away - in almost total darkness!", "Ang Philippine eagle-owl ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature moonlight guardian behavior", WildlifeActivityPeriod.NOCTURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_luzon_scops_owl", "animal_photo_bird_luzon_scops_owl", "Luzon scops owl", "Luzon scops owl", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "This tiny owl is only as tall as a pencil - but its hoot can echo through the whole forest!", "Ang Luzon scops owl ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature little night scout behavior", WildlifeActivityPeriod.NOCTURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_rufous_hornbill", "animal_photo_bird_rufous_hornbill", "Rufous hornbill", "Rufous hornbill", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its bright red bill looks heavy but is actually hollow - like a lightweight trumpet made of keratin!", "Ang Rufous hornbill ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature big-bill banner behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_visayan_hornbill", "animal_photo_bird_visayan_hornbill", "Visayan hornbill", "Visayan hornbill", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "When it flies, its wings make a loud whooshing sound you can hear from 100 meters away!", "Ang Visayan hornbill ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature forest trumpeter behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_mindoro_bleeding_heart", "animal_photo_bird_mindoro_bleeding_heart", "Mindoro bleeding-heart", "Mindoro bleeding-heart", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It has a bright red patch on its chest shaped just like a heart - nature's own Valentine!", "Ang Mindoro bleeding-heart ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature heart feather behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_negros_bleeding_heart", "animal_photo_bird_negros_bleeding_heart", "Negros bleeding-heart", "Negros bleeding-heart", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Sky Scouts", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its ruby-red chest feather glows in the sunlight, earning it the nickname 'the jewel of the forest.'", "Ang Negros bleeding-heart ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature ruby heart behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_cebu_flowerpecker", "animal_photo_bird_cebu_flowerpecker", "Cebu flowerpecker", "Cebu flowerpecker", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's so rare that scientists thought it was extinct for 80 years - until someone spotted one in 1992!", "Ang Cebu flowerpecker ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature cebu scarlet spot behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_scarlet_collared_flowerpecker", "animal_photo_bird_scarlet_collared_flowerpecker", "Scarlet-collared flowerpecker", "Scarlet-collared flowerpecker", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its bright red collar looks like a tiny superhero cape - and it zips through flowers just as fast!", "Ang Scarlet-collared flowerpecker ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature mindoro red collar behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_flame_breasted_fruit_dove", "animal_photo_bird_flame_breasted_fruit_dove", "Flame-breasted fruit-dove", "Flame-breasted fruit-dove", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its chest blazes with fiery orange feathers - but it's a gentle fruit eater that wouldn't hurt a fly!", "Ang Flame-breasted fruit-dove ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature flame chest flyer behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_black_hooded_coucal", "animal_photo_bird_black_hooded_coucal", "Black-hooded coucal", "Black-hooded coucal", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It wears a natural black hood like a mysterious forest detective - always watching from the bushes!", "Ang Black-hooded coucal ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature forest hood behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_cebu_black_shama", "animal_photo_bird_cebu_black_shama", "Cebu black shama", "Cebu black shama", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its song is so beautiful and complex that it can copy the sounds of other birds and even car alarms!", "Ang Cebu black shama ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature cebu song star behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_philippine_creeper", "animal_photo_bird_philippine_creeper", "Philippine creeper", "Philippine creeper", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It climbs tree trunks spiraling upward like a tiny feathered screwdriver - never sliding down!", "Ang Philippine creeper ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature stripe-breast climber behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_philippine_trogon", "animal_photo_bird_philippine_trogon", "Philippine trogon", "Philippine trogon", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Males have a bright pink-red belly so vivid that local people call it the 'forest flame.'", "Ang Philippine trogon ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature ruby belly behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_whiskered_pitta", "animal_photo_bird_whiskered_pitta", "Whiskered pitta", "Whiskered pitta", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It has tiny feather whiskers near its beak - like a wise old forest wizard with a colorful robe!", "Ang Whiskered pitta ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature whisker walker behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_palawan_tit", "animal_photo_bird_palawan_tit", "Palawan tit", "Palawan tit", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its bright yellow cap looks like a tiny splash of sunshine - and it never sits still for long!", "Ang Palawan tit ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature palawan sun cap behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_bird_fairy_bluebird", "animal_photo_bird_fairy_bluebird", "Philippine fairy-bluebird", "Philippine fairy-bluebird", "sanctuary-lookout", "sanctuary-nest", "Living Sanctuary / Songbird Grove", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its feathers are an electric sapphire blue so intense it looks like it flew through a rainbow!", "Ang Philippine fairy-bluebird ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature sapphire spark behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
        species("badge_reptile_philippine_crocodile", "animal_photo_reptile_philippine_crocodile", "Philippine crocodile", "Buwayang Pilipino", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's one of the rarest crocodiles on Earth - with a golden-brown color that sparkles in the sun!", "Ang Buwayang Pilipino ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature river guardian behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_forest_turtle", "animal_photo_reptile_forest_turtle", "Philippine forest turtle", "Philippine forest turtle", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "The pattern on its shell looks exactly like a gentleman's bow tie - very formal for a turtle!", "Ang Philippine forest turtle ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature bow-tie turtle behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_sierra_madre_monitor", "animal_photo_reptile_sierra_madre_monitor", "Northern Sierra Madre forest monitor", "Northern Sierra Madre forest monitor", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It can grow longer than a baseball bat and loves climbing high into the forest treetops!", "Ang Northern Sierra Madre forest monitor ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature canopy giant behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_panay_monitor", "animal_photo_reptile_panay_monitor", "Panay monitor lizard", "Panay monitor lizard", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "This lizard is a champion climber - it spends most of its life in the trees eating fruit!", "Ang Panay monitor lizard ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature panay tree explorer behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_grays_monitor", "animal_photo_reptile_grays_monitor", "Gray's monitor", "Gray's monitor", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Unlike most lizards, this one loves eating fruit - making it a forest gardener that plants seeds!", "Ang Gray's monitor ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature forest fruit finder behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_philippine_cobra", "animal_photo_reptile_philippine_cobra", "Philippine cobra", "Philippine cobra", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It can spread its neck into a wide hood wider than a dinner plate - but would rather slither away than fight!", "Ang Philippine cobra ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature hood helper behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_samar_cobra", "animal_photo_reptile_samar_cobra", "Samar cobra", "Samar cobra", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Found only on Samar island, this cobra helps farmers by eating rats that damage rice fields!", "Ang Samar cobra ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature island hood behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_flying_lizard", "animal_photo_reptile_flying_lizard", "Philippine flying lizard", "Philippine flying lizard", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It can't truly fly, but it glides between trees using skin flaps - like a tiny dragon with no fire!", "Ang Philippine flying lizard ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature tree glider behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_sailfin_lizard", "animal_photo_reptile_sailfin_lizard", "Philippine sailfin lizard", "Philippine sailfin lizard", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "The fin on its back stands up like a sail when it swims - and it can even run across water!", "Ang Philippine sailfin lizard ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature sail-back swimmer behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_reptile_box_turtle", "animal_photo_reptile_box_turtle", "Philippine box turtle", "Philippine box turtle", "sanctuary-wildlife-sign", "sanctuary-shelter", "Living Sanctuary / River Guardians", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its shell has special hinges that let it close up completely tight - like locking a tiny front door!", "Ang Philippine box turtle ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature shell door keeper behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_amphibian_mindoro_tree_frog", "animal_photo_amphibian_mindoro_tree_frog", "Mindoro tree frog", "Mindoro tree frog", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its sticky toe pads let it climb straight up tree trunks - no slipping, even in the rain!", "Ang Mindoro tree frog ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature tree-top hopper behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_amphibian_mindanao_fanged_frog", "animal_photo_amphibian_mindanao_fanged_frog", "Mindanao fanged frog", "Mindanao fanged frog", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Those 'fangs' are actually little bone bumps on its jaw - it looks tough but only eats bugs!", "Ang Mindanao fanged frog ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature forest fang behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_amphibian_flat_headed_frog", "animal_photo_amphibian_flat_headed_frog", "Philippine flat-headed frog", "Philippine flat-headed frog", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its head is so flat it can squeeze under rocks in fast streams - the original pancake frog!", "Ang Philippine flat-headed frog ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature stream pancake behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_amphibian_luzon_narrow_mouthed_frog", "animal_photo_amphibian_luzon_narrow_mouthed_frog", "Luzon narrow-mouthed frog", "Luzon narrow-mouthed frog", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's round and tiny like a pebble - perfect for hiding among rocks by the stream!", "Ang Luzon narrow-mouthed frog ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature little pebble behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_amphibian_wrinkled_ground_frog", "animal_photo_amphibian_wrinkled_ground_frog", "Philippine wrinkled ground frog", "Philippine wrinkled ground frog", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its wrinkly skin helps it blend into dead leaves on the forest floor - the master of disguise!", "Ang Philippine wrinkled ground frog ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature wrinkle walker behavior", WildlifeActivityPeriod.CREPUSCULAR, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_fish_tawilis", "animal_photo_fish_tawilis", "Tawilis", "Tawilis", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's the only freshwater sardine in the world - found only in Taal Lake, nowhere else on Earth!", "Ang Tawilis ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature lake silver flash behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_fish_silver_therapon", "animal_photo_fish_silver_therapon", "Silver therapon", "Silver therapon", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its shiny silver body reflects light underwater like a mirror - helping it hide from predators!", "Ang Silver therapon ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature silver swimmer behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_fish_sinarapan", "animal_photo_fish_sinarapan", "Sinarapan", "Sinarapan", "sanctuary-pond", "sanctuary-shelter", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "It's one of the smallest fish in the world - you could fit 10 of them on your thumb!", "Ang Sinarapan ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature tiny glass fish behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.CORAL_LAGOON_FRESHWATER_STREAM),
        species("badge_butterfly_luzon_peacock_swallowtail", "animal_photo_butterfly_luzon_peacock_swallowtail", "Luzon peacock swallowtail", "Luzon peacock swallowtail", "sanctuary-butterfly", "sanctuary-flower-bed", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its wings flash iridescent green and blue like a peacock feather - but this beauty lives high in the mountains!", "Ang Luzon peacock swallowtail ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature mountain rainbow behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_butterfly_golden_birdwing", "animal_photo_butterfly_golden_birdwing", "Golden birdwing", "Golden birdwing", "sanctuary-butterfly", "sanctuary-flower-bed", "Living Sanctuary / Creek Coral", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "Its gold-tipped wings are as wide as a small bird's - and they shimmer like liquid gold in flight!", "Ang Golden birdwing ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature golden glider behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.EMERALD_FOREST_MEADOW),
        species("badge_milestone_first_steps", "animal_photo_bird_eagle", "First Steps", "First Steps", "sanctuary-reading-nest", "sanctuary-tree", "Living Sanctuary / Milestone", "Buhay na Santuwaryo / Tirahan sa Pilipinas", "You finished your very first lesson! Every big adventure starts with one brave first step - and you just took it. Milo is so proud of you!", "Ang First Steps ay mahalagang bahagi ng kalikasan sa Pilipinas. Ang pagkilos at tirahan nito ay tumutulong sa balanse ng ekosistema.", "Shows its signature bright beginning behavior", WildlifeActivityPeriod.DIURNAL, SanctuaryBiomeZone.HIGH_CANOPY_CLOUD_SUMMIT),
    )
    init {
        require(species.size == 51) { "The sanctuary catalog must contain all 51 badges" }
        require(species.map { it.badgeId }.toSet().size == species.size) { "Duplicate sanctuary badge" }
        require(species.all { it.primaryHabitatId in validHabitatIds && it.alternateHabitatId in validHabitatIds }) { "Unknown sanctuary habitat" }
    }
    fun byBadgeId(id: String) = species.firstOrNull { it.badgeId == id }
    fun requireByBadgeId(id: String) = requireNotNull(byBadgeId(id)) { "Unknown sanctuary badge: $id" }
    fun byAnimalAssetId(id: String) = species.firstOrNull { it.animalAssetId == id }
    fun inZone(zone: SanctuaryBiomeZone) = species.filter { it.biomeZone == zone }
    private fun species(badgeId:String,assetId:String,en:String,fil:String,primary:String,alternate:String,habitatEn:String,habitatFil:String,factEn:String,factFil:String,behavior:String,period:WildlifeActivityPeriod,zone:SanctuaryBiomeZone)= WildlifeHabitatAffinity(badgeId,assetId,en,fil,primary,alternate,habitatEn,habitatFil,factEn,factFil,behavior,period,zone)
}
